server:
  port: 8080

spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"

zuul:
  ignored-services: "*"
  prefix: /api/project1
  strip-prefix: false
  routes:
    service1:
      path: /service1/**
      serviceId: service1
      strip-prefix: false
    service2:
      path: /service2/**
      serviceId: service2
      strip-prefix: false